services:

  app:
    build: .
    command: python manage.py garmin_upload
    volumes:
      - .:/app:delegated
      - /dev/bus/usb:/dev/bus/usb
      - ./garmin_data:/data    
    privileged: true
    tty: true
    stdin_open: true
    environment:
      GARMIN_SAVE_RUNS: "/data"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/hiker_db"
    depends_on:
      - db

  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5020:5432"