services:

  app:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             uwsgi --ini uwsgi.ini"
    volumes:
      - .:/app:delegated
      - /dev/bus/usb:/dev/bus/usb
      - ./garmin_data:/data
    ports:
      - "8001:8001"
    privileged: true
    tty: true
    stdin_open: true
    environment:
      DJANGO_SETTINGS_MODULE: "hike_tracker.settings"
      GARMIN_SAVE_RUNS: "/data"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/hiker_db"
    depends_on:
      - db

  db:
    build: ./db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5020:5432"

volumes:
  postgres_data:
    driver: local

