# Generated by Django 5.2.4 on 2025-07-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling')], max_length=20)),
                ('sport', models.CharField(max_length=20)),
                ('multisport', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('distance', models.FloatField()),
                ('trigger', models.CharField(max_length=20)),
                ('begin_lat', models.FloatField()),
                ('begin_lon', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lon', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('calories', models.IntegerField()),
                ('intensity', models.CharField(max_length=20)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='importer.run')),
            ],
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('alt', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('lap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_points', to='importer.lap')),
            ],
        ),
    ]
