# Generated by Django 5.2.4 on 2025-07-06 20:50

import django.db.models.deletion
import importer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.UUIDField(default=importer.models.create_uuid, primary_key=True, serialize=False)),
                ('file_name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.UUIDField(default=importer.models.create_uuid, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('alt', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='importer.hike')),
            ],
        ),
    ]
