# Generated by Django 5.2.4 on 2025-07-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hike',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
