# Generated by Django 5.2.4 on 2025-07-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_hike_description_hike_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackpoint',
            name='altitude',
            field=models.FloatField(null=True),
        ),
    ]
