# Generated by Django 5.2.4 on 2025-07-24 00:11

import importer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_trackpoint_altitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateZone',
            fields=[
                ('id', models.UUIDField(default=importer.models.create_uuid, primary_key=True, serialize=False)),
                ('mhr', models.IntegerField(verbose_name='Maximum Heart Rate')),
                ('rhr', models.IntegerField(verbose_name='Resting Heart Rate')),
                ('zone_1', models.IntegerField(editable=False)),
                ('zone_2', models.IntegerField(editable=False)),
                ('zone_3', models.IntegerField(editable=False)),
                ('zone_4', models.IntegerField(editable=False)),
                ('zone_5', models.IntegerField(editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
